### ISSUE TITLE
Multiple (European?) resorts broken due to changed links

### ISSUE THREAD

**Issue by mdjong1** [pirxpilot/liftie#40]
Multiple resorts appear to be broken due to links that have changed. This might be something Covid related, and could be different in the following season, so might not be high priority at the moment.

Resorts checked:
- Les Arcs
- La Plagne
- Kitzbuehel
- Les Menuires
- Meribel

**Comment by pirxpilot** [comment]
Yup. You can see the list of resorts without the list status at the https://liftie.info/absent
I pretty much skipped the usual round of updates before the skiing season because - especially in Europe - it did not look like there would be a skiing season...
I am closing this issue. Not because those resorts are now magically fixed. But because it does not really make sense to track various unrelated breakages here.
That should not discourage folks from sending PRs for any resorts they want to see fixed or improved.
